### PR TITLE
Version change to 0.0.4

### PR DESCRIPTION
**Pull request by chandraprakash**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/accumulator/16)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[README.md, line 24 [r1]](https://reviewable.io:443/reviews/maidsafe/accumulator/16#-JuC3K1IQ5Jse1D0-9iy)** ([raw file](https://github.com/maidsafe/accumulator/blob/6b1f4fd0c29381fb5d6a5e79e7ae7fae5e116cf9/README.md#L24)):</sup>
Incorrect Task label

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/accumulator/16)

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/accumulator/16)

**Pull request merged**
